# Generated by Django 5.0.2 on 2024-02-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0002_cocktailliste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strDrink', models.CharField(max_length=200)),
                ('strDrinkThumb', models.CharField(max_length=255)),
                ('idDrink', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='cocktailliste',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='CocktailIndexPage',
        ),
        migrations.DeleteModel(
            name='CocktailListe',
        ),
    ]
