# Generated by Django 5.0.2 on 2024-02-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0005_cocktail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktailpage',
            name='ingredients',
            field=models.JSONField(default=list),
        ),
    ]
