# Generated by Django 5.0.2 on 2024-02-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0007_cocktail_image_cocktail_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='category',
            field=models.CharField(default='Cocktail', max_length=50),
        ),
        migrations.AddField(
            model_name='cocktailpage',
            name='category',
            field=models.CharField(default='Cocktail', max_length=50),
        ),
    ]
