# Generated by Django 5.0.2 on 2024-02-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0008_cocktail_category_cocktailpage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cocktailpage',
            name='category',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='alcoholic',
            field=models.CharField(default='Alcoholic', max_length=50),
        ),
        migrations.AddField(
            model_name='cocktailpage',
            name='strAlcoholic',
            field=models.CharField(default='Alcoholic', max_length=50),
        ),
    ]
