# Generated by Django 5.0.2 on 2024-02-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0009_remove_cocktail_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='instructions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cocktailpage',
            name='strInstructions',
            field=models.TextField(default=''),
        ),
    ]
