# Generated by Django 5.0.2 on 2024-02-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0010_cocktail_instructions_cocktailpage_strinstructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
