# Generated by Django 5.0.2 on 2024-02-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0011_alter_cocktail_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='ingredients',
            field=models.JSONField(default=list),
        ),
    ]
