# Generated by Django 5.0.2 on 2024-02-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0012_cocktailtagindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailpage',
            name='ingredients',
            field=models.JSONField(default={'strIngredient1': 'water', 'strIngredient2': 'salt'}),
        ),
    ]
