# Generated by Django 5.0.2 on 2024-02-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0013_alter_cocktail_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cocktail_images'),
        ),
    ]
