# Generated by Django 5.0.2 on 2024-02-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0014_alter_cocktailpage_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailpage',
            name='ingredients',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
